from distutils.core import setup, Extension
import numpy.distutils.misc_util

cc_segmenter = Extension("cc_segmenter",
                         sources=["base/Pitch.cpp",
                                  "dsp/chromagram/Chromagram.cpp",
                                  "dsp/chromagram/ConstantQ.cpp",
                                  "dsp/keydetection/GetKeyMode.cpp",
                                  "dsp/mfcc/MFCC.cpp",
                                  "dsp/onsets/DetectionFunction.cpp",
                                  "dsp/onsets/PeakPicking.cpp",
                                  "dsp/phasevocoder/PhaseVocoder.cpp",
                                  "dsp/rateconversion/Decimator.cpp",
                                  "dsp/rhythm/BeatSpectrum.cpp",
                                  "dsp/segmentation/cluster_melt.c",
                                  "dsp/segmentation/ClusterMeltSegmenter.cpp",
                                  "dsp/segmentation/cluster_segmenter.c",
                                  "dsp/segmentation/Segmenter.cpp",
                                  "dsp/signalconditioning/DFProcess.cpp",
                                  "dsp/signalconditioning/Filter.cpp",
                                  "dsp/signalconditioning/FiltFilt.cpp",
                                  "dsp/signalconditioning/Framer.cpp",
                                  "dsp/tempotracking/DownBeat.cpp",
                                  "dsp/tempotracking/TempoTrack.cpp",
                                  "dsp/tempotracking/TempoTrackV2.cpp",
                                  "dsp/tonal/ChangeDetectionFunction.cpp",
                                  "dsp/tonal/TCSgram.cpp",
                                  "dsp/tonal/TonalEstimator.cpp",
                                  "dsp/transforms/FFT.cpp",
                                  "dsp/wavelet/Wavelet.cpp",
                                  "hmm/hmm.c",
                                  "maths/Correlation.cpp",
                                  "maths/CosineDistance.cpp",
                                  "maths/KLDivergence.cpp",
                                  "maths/MathUtilities.cpp",
                                  "maths/pca/pca.c",
                                  "thread/Thread.cpp",
                                  "main.cpp"
                                  ],
                         include_dirs=["dsp/segmentation",
                                       ".",
                                       "include"],
                         libraries=["jsoncpp",
                                    "stdc++"],
                         extra_compile_args=["-DUSE_PTHREADS"],
                         extra_link_args=["-framework Accelerate"],
                         language=["c++"])

setup(ext_modules=[cc_segmenter],
      include_dirs=numpy.distutils.misc_util.get_numpy_include_dirs())
